name: Build Android app
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

jobs:
  build:
    name: flutter build apk
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Install packages
        run: flutter pub get
      - name: Build app
        run: flutter build apk
