name: Lint
on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
      - ".git*"
      - ".vscode/**"

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Install packages
        run: flutter pub get
      - name: Run analyze
        run: flutter analyze
